version: "3.8"

services:
  db:
    image: postgres:14
    container_name: postgres_db
    ports:
      - "5433:5432"
    environment:
      POSTGRES_USER: dedoxify
      POSTGRES_PASSWORD: dedoxify
      POSTGRES_DB: dedoxify
    volumes:
      - pg_data:/var/lib/postgresql/data
      - ./initdb:/docker-entrypoint-initdb.d

volumes:
  pg_data:
